server:
  port: 8081
spring:
  profiles:
    include:
      - db
  application:
    name: cardProject
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  security:
    user:
      name: admin
      password: 1234
      roles: ADMIN