server:
  port: 8081
spring:
  profiles:
    include:
      - db
  application:
    name: cardProject
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  security:
    user:
      name: admin
      password: 1234
      roles: ADMIN
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 1000MB
file:
  path: D:\upload\cardFolder\