spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springjae234
    password: 1234
mybatis:
  config-location: classpath:mybatis/config/config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.definejae234.cardproject.card.dto
